# Generated by Django 3.2.18 on 2023-09-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hng_stage2_app', '0002_auto_20230913_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
